name: Notification Service CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Notification Service
        working-directory: notification-service
        run: |
          chmod +x mvnw
          ./mvnw clean install